name: faker_app_flutter_firebase
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: 1.0.8
  flutter_riverpod: 2.5.1
  go_router: 14.1.1
  equatable: 2.0.5
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  firebase_ui_auth: ^1.16.0
  cloud_firestore: ^5.4.5
  faker: ^2.2.0
  firebase_ui_firestore: ^1.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 4.0.0

flutter:
  uses-material-design: true

# Since we’ll use the ProfileScreen widget, we should also add the following:
fonts:
  - family: SocialIcons
    fonts:
      - asset: packages/firebase_ui_auth/fonts/SocialIcons.ttf
